### ISSUE TITLE
Don't works with Shelly 1 PM

### ISSUE THREAD

**Issue by FRUCHTiii** [edekeijzer/OctoPrint-PSUControl-Shelly#4]
I don't get this plugin running with my Shelly 1 PM.
I tried it locally and with Shelly Cloud both versions won't work.

The pi and plugin can connect correctly to the shelly. The PSU control updates the current status correct if I switch the Shelly manually.
I also done a tcpdump on the pi.
If I try to change the power state within the tcpdump there is no url that is called for power on/off the shelly.
Only the update status every 5 seconds is working and requested.

I don't get it what I'm doing wrong.

[shelly.log](https://github.com/edekeijzer/OctoPrint-PSUControl-Shelly/files/6583377/shelly.log)
<img width="697" alt="Bildschirmfoto 2021-06-02 um 11 31 23" src="https://user-images.githubusercontent.com/57792137/120456666-1f259700-c396-11eb-85b9-9b35c12cc354.png">
<img width="732" alt="Bildschirmfoto 2021-06-02 um 11 31 17" src="https://user-images.githubusercontent.com/57792137/120456677-20ef5a80-c396-11eb-8df9-e64f6acfead9.png">

**Comment by edekeijzer** [comment]
@FRUCHTiii did you notice the red bar in your screenshot? ;) The sensing is set to Shelly, which is why it does follow the state of your Shelly, but the switching method is still at Gcode commands, which is why it does not send commands to the Shelly when you hit the power button.
Also note that the Auto On function could lead to issues, as the author of the original PSUControl plugin explains [here](https://github.com/edekeijzer/OctoPrint-PSUControl-HomeAssistant/issues/4#issuecomment-846396693). The plugin will send a switching command each time one of the specified Gcodes is processed, which will cause an issue when the target is unavailable (for example, a short hiccup in wifi connectivity) as it will wait for the printer to turn on. My advice would be to turn it off when using the Shelly plugin.

**Comment by FRUCHTiii** [comment]
I'm feel like a fool.
Thanks for your help.
